name: RNN

dependencies:
  - python>=3.8
  - ipython
  - ipykernel

  - numpy
  - scipy
  - pandas>=2.0.0
  - pytables
  - matplotlib

  # The below should only be run on a node with a GPU!
  - conda-forge::cudatoolkit>=11.8
  - nvidia::cuda>=11.8

  # Example of installing pytorch & torchvision
  - pytorch::pytorch-cuda>=11.8
  - pytorch::pytorch>=1.7.1
  - pytorch::torchvision>=0.15

  - pip
